name: Manual # 手动触发

on:
  workflow_dispatch:  # 手动触发

jobs: #任务
  docker-build:
    runs-on: ubuntu-latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 核对仓库
        uses: actions/checkout@v2

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登陆 Docker Hub
        uses: docker/login-action@v3 # v2.1.0 GitHub 的 docker-login @后面可为版本、也可为哈希值
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: 构建镜像并上传 tag
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: mutouloves/rustdesk-api:${{steps.vars.outputs.DOCKER_TAG}}

      - name: 构建镜像并上传 latest
        id: docker_buildx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: mutouloves/rustdesk-api:latest
